-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               8.3.0 - Homebrew
-- Server OS:                    macos14.2
-- HeidiSQL Version:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for franchise
CREATE DATABASE IF NOT EXISTS `franchise` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `franchise`;

-- Dumping structure for table franchise.FRANCHISES
CREATE TABLE IF NOT EXISTS `FRANCHISES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data exporting was unselected.

-- Dumping structure for table franchise.PRODUCTS
CREATE TABLE IF NOT EXISTS `PRODUCTS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data exporting was unselected.

-- Dumping structure for table franchise.SUBSIDIARIES
CREATE TABLE IF NOT EXISTS `SUBSIDIARIES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FRANCHISE_ID` int NOT NULL,
  `NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_FRANCHISE_HAS_SUBSIDIARIES` (`FRANCHISE_ID`),
  CONSTRAINT `FK_FRANCHISE_HAS_SUBSIDIARIES` FOREIGN KEY (`FRANCHISE_ID`) REFERENCES `FRANCHISES` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data exporting was unselected.

-- Dumping structure for table franchise.SUBSIDIARY_PRODUCTS_STOCK
CREATE TABLE IF NOT EXISTS `SUBSIDIARY_PRODUCTS_STOCK` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SUBSIDIARY_ID` int NOT NULL,
  `PRODUCT_ID` int NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `SUBSIDIARY_PRODUCT_UNIQUE` (`SUBSIDIARY_ID`,`PRODUCT_ID`),
  KEY `FK_PRODUCT_HAS_SUBSIDIARY_STOCK` (`PRODUCT_ID`),
  CONSTRAINT `FK_PRODUCT_HAS_SUBSIDIARY_STOCK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`ID`),
  CONSTRAINT `FK_SUBSIDIARY_HAS_PRODUCT_STOCK` FOREIGN KEY (`SUBSIDIARY_ID`) REFERENCES `SUBSIDIARIES` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data exporting was unselected.

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
